language: ruby
env:
  - CODECLIMATE_REPO_TOKEN=f7c652b65a700fcf1032174afc5ea243b991e48bf73077cc34c148e1c800a2f7
bundler_args: --without sql benchmarks development
script: "bundle exec rake spec"
rvm:
  - 2.0
  - 2.1
  - rbx-2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
