language: ruby
dist: trusty
sudo: required
cache: bundler
install:
  - "cd core && bundle install --without sql benchmarks console tools"
  - "cd mapper && bundle install --without sql benchmarks console tools"
  - "cd repository && bundle install --without sql benchmarks console tools"
before_script:
  - "psql -c 'create database rom_repository' -U postgres"
script: "cd $TRAVIS_BUILD_DIR && rake spec"
after_succes:
  - bundle exec codeclimate-test-reporter
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
