language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without sql benchmarks console tools
script: "bundle exec rake ci"
after_success:
  - '[ "$TRAVIS_RUBY_VERSION" = "2.3.1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1
  - 2.2
  - 2.3.1
  - rbx-3
  - jruby-9.1.5.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - COVERAGE='true'
matrix:
  allow_failures:
    - rvm: rbx-3
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
