language: ruby
dist: trusty
sudo: required
cache: bundler
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_repository' -U postgres
script: "bundle exec rake ci"
after_success:
  - '[ "$TRAVIS_RUBY_VERSION" = "2.3.1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.1
  - 2.2
  - 2.3
  - rbx-3
  - jruby-9.1.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  include:
    - rvm: jruby-head
      before_install: gem install bundler --no-ri --no-rdoc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
