language: ruby
sudo: false
cache: bundler
env:
  - CODECLIMATE_REPO_TOKEN=f7c652b65a700fcf1032174afc5ea243b991e48bf73077cc34c148e1c800a2f7
bundler_args: --without sql benchmarks console tools
script: "bundle exec rake ci"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - rbx-2
  - jruby-9000
  - ruby-head
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: jruby-head
      before_install: gem install bundler --no-ri --no-rdoc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
