language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rake metrics:coverage"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - rbx-2
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: 2.1.0
notifications:
  irc:
    channels:
      - "irc.freenode.org#rom-rb"
    on_success: never
    on_failure: change
  email:
    on_success: never
    on_failure: change
