language: ruby
bundler_args: --without yard guard benchmarks
script: "bundle exec rspec spec/integration"
rvm:
  - 2.0.0
  - 2.1.2
  - rbx-2
  - jruby
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
