version: '3'

services:
  rom:
    build:
      context: .
      args:
        RUBY_VERSION: ${RUBY_VERSION:-3.0}
    env_file: [.env, .env.local]
    entrypoint: /bin/bash -c '(bundle check || bundle) && tail -f Gemfile'
    volumes:
      - .:/usr/local/src/rom
      - bundle:/usr/local/bundle
    depends_on: [db]
    links: [db]

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: rom
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  bundle:
