jobs:
  tests:
    services:
      db:
        image: postgres:10.8
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: rom_repository
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        use_use_rom_sql_master:
          - 'true'
        ruby:
          - "3.0"
          - "2.7"
          - "2.6"
          - "2.5"
          - "jruby"
          - "truffleruby"
        include:
          - ruby: "3.0"
            coverage: "true"
            use_dry_transformer_master: "true"
    env:
      COVERAGE: ${{matrix.coverage}}
      BASE_DB_URI: localhost/rom_repository
      USE_DRY_TRANSFORMER_MASTER: ${{matrix.use_dry_transformer_master}}
      USE_ROM_SQL_MASTER: ${{matrix.use_rom_sql_master}}
      CODACY_RUN_LOCAL: ${{matrix.coverage}}
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
      APT_DEPS: "libpq-dev libsqlite3-dev"
